/* This file is automatically generated. DO NOT EDIT! */

#ifndef _ricker1_h
#define _ricker1_h


float Ricker(float t, float f0, float t0, float A);
/*< ricker wavelet:
 * f0: peak frequency
 * t0: time lag
 * A: amplitude
 * ************************>*/

#endif
